services:
  qme-auth: 
    build: 
      context: .
      dockerfile: Dockerfile.authservice
    environment: 
     - PORT=3010
     - MONGODB_HOST=qme-auth-db
     - MONGODB_PORT=27017
     - MONGODB_DATABASE_NAME=auth
     - DEFAULT_ADMIN_USER=admin
     - INITIAL_ADMIN_PASSWORD=changeMeNow!!!
     - JWT_SECRET=notVerySecret!!!
     - CORS_ALLOWED_ORIGIN=http://localhost:3000
    ports: 
     - "3010:3010"
  qme-auth-db:
    image: mongo:latest
    volumes: 
     - "qme-auth-db-volume:/data/db"
    ports: 
     - "27017:27017"
  qme-auth-reverse-proxy:
    build: 
      context: .
      dockerfile: Dockerfile.reverseproxy
    ports:
     - 8010:8010
    restart: always
volumes:
  qme-auth-db-volume: